version: 0.2
phases:
  pre_build:
    commands:
      - echo install nginx
      - sudo apt update -y
      - sudo apt install nginx -y
  build:
    commands:
      - echo build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo configure nginx
# artifacts:
#   files
#     - /var/www/html/index.html
