version: 0.2
phases:
  pre-build:
    commands:
      - echo install nginx
      - sudo apt update -y
      - sudo apt install nginx -y
  build:
    commands:
      - echo build started on `date`
      - cp index.html /var/www/html/
  post build:
    commands:
      - echo configure nginx
artifacts:
  files
    - /var/www/html/index.html
